### ISSUE TITLE
Refer the vclick warning in tap event documentation

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/api.jquerymobile.com#132]
The "Use vclick with caution" warning here http://api.jquerymobile.com/vclick/ also goes for the ```tap``` event because it uses ```vclick```. We have to point to that warning on the http://api.jquerymobile.com/tap/ page.

**Comment by agcolom** [comment]
@jaspermdegroot hoping to catchup with these issues this week... For this one, Is it a matter of replicating the warning in [http://api.jquerymobile.com/vclick/](http://api.jquerymobile.com/vclick/) (Warning: Use vclick with caution) and change the `vclick` with `tap` in this one? Thanks

**Comment by jaspermdegroot** [comment]
@agcolom 

Maybe it's better to add a warning to ```tap``` that says that it uses ```vclick``` so the warning there (with a link to the ```vclick``` page) also applies to ```tap```. That way we don't have to maintain the long warning text at two places. Thanks!

**Comment by agcolom** [comment]
@jaspermdegroot perfect. Thanks
