### ISSUE TITLE
Documentation 1.4: description for hideUrlBar is missing 

### ISSUE THREAD

**Issue by Ruffio** [jquery/api.jquerymobile.com#203]
hideUrlBar is missing description in API documentation: http://api.jquerymobile.com/global-config/

$.mobile.hideUrlBar is mentioned in 1.4 ChangeLog so it should be described in API doc.

**Comment by agcolom** [comment]
@arschmitz Should hideUrlBar be described in the [global config](http://api.jquerymobile.com/global-config/) page? If the answer is yes, would we say something like:
hideUrlBar boolean, default: false
hides the address bar if set to true 

??

**Comment by arschmitz** [comment]
It should be but it should also be marked as deprecated. We are deprecating in 1.5 removing in 1.6 it no longer works on iOS and other places due to changes in how these work natively.
