### ISSUE TITLE
Panel supports markup outside the page container, docs never mention this

### ISSUE THREAD

**Issue by jzaefferer** [jquery/api.jquerymobile.com#208]
One of the more recent improvements to Panel was support for using it outside a page container. That still seems to be working in 1.4.0, but doesn't get mentioned at all in the API docs. 

In contrast, the "Where panel markup goes in a page" section describes that the panel markup *must* be somewhere inside the `role=page` element.

**Comment by agcolom** [comment]
This is now documented via https://github.com/jquery/api.jquerymobile.com/commit/df39411d6e577625134aa141e38401a02c46a266  so I believe this issue can be closed
