### ISSUE TITLE
Deprecated note missing for buttonMarkup method

### ISSUE THREAD

**Issue by jaspermdegroot** [jquery/api.jquerymobile.com#212]
buttonMarkup has been deprecated but there is no note about this here: http://api.jquerymobile.com/buttonMarkup/

**Comment by arthurvr** [comment]
On the page there now is:

> Note: .buttonMarkup() is deprecated as of jQuery Mobile 1.4.0 and will be removed in 1.5.0. You can now assign the full range of button style options to your button or a elements by simply adding classes.

@jaspermdegroot @gabrielschulhof I guess https://github.com/jquery/api.jquerymobile.com/commit/208ce191c94d2cda7bcc5760a604236665f27087 fixed this issue?

**Comment by jaspermdegroot** [comment]
@arthurvr 

Yes indeed. Not sure why it wasn't visible on the site yet when I opened this issue, because that commit is older than this ticket. Anyway, closing as fixed.
Thanks!
