### ISSUE TITLE
Configuring defaults is hard to find

### ISSUE THREAD

**Issue by frequent** [jquery/api.jquerymobile.com#322]
Just wondering - Doesn't the `Configuring Defaults` section warrant to be on the side menu? 

It's super difficult to find - yet so important, so please consider adding it to the side menu.

([This](http://api.jquerymobile.com/global-config/) is the page I'm talking about)

**Comment by agcolom** [comment]
I think being under reference is ok. I'm closing for now. We can reopen if someone feels otherwise.
