### ISSUE TITLE
use of $( ".selector" ) in the documentation is confusing

### ISSUE THREAD

**Issue by snowch** [jquery/api.jquerymobile.com#363]
The API documents heavily use ```$( ".selector" )```, but for a beginner of jquery mobile, it is not clear what element you should be selecting.

For example, in the [Pagecontainer documentation](http://api.jquerymobile.com/pagecontainer/), should the element be ```$(document)```, ```$('body')```, ```$(":mobile-pagecontainer")```, or something else?

**Comment by arschmitz** [comment]
I agree we should use something more realistic here

**Comment by arschmitz** [comment]
I no longer agree with my self from April `.selector` is correct here there is no single correct selector and this is what is used through out all our docs here and also in UI and Core. 

I am going to close this as won't fix
