### ISSUE TITLE
How to deploy?

### ISSUE THREAD

**Issue by pei-han** [jquery/api.jquerymobile.com#375]

**Comment by arthurvr** [comment]
How to deploy what? This website? There are instructions on the [contributing guide](http://contribute.jquery.org/web-sites/#local-development) for that.

**Comment by pei-han** [comment]
yes,how to deploy the api.jquerymobile.com,then access this website locally
My english is so bad,do u understand?

**Comment by pei-han** [comment]
Does that use nodejs to build and deploy this website?

**Comment by arthurvr** [comment]
You can find a guideline on the site I linked to. I'm going to close this issue as it's more of a question, not really an issue.

> Does that use nodejs to build and deploy this website?

We use Grunt to deploy to the Wordpress instance.

**Comment by pei-han** [comment]
Ok,
thx
