### ISSUE TITLE
Version mixup between doc entry page (1.4.5) and API (1.5)

### ISSUE THREAD

**Issue by jtara** [jquery/api.jquerymobile.com#410]
https://jquerymobile.com/ currently provides documentation for the currently released version, 1.4.5.

If you click on the API Documentation tab, you navigated to API documentation for unreleased alphia 1.5.

**Comment by jtara** [comment]
Perhaps related to #409?

**Comment by apsdehal** [comment]
This is correct. As docs were updated for 1.5. It is ready to be released once few hurdles get cleared. To use 1.4.5 documentation click on 1.4.5 tab.

**Comment by jtara** [comment]
There is no way to get there, unless you know the URL.

Follow this sequence:

1. Navigate to https://api.jquerymobile.com/
2. Click on the link for jQuery Mobile 1.4 API Documentation
3. This lands you on an overview API documentation page
4. There are no categories listed. (See also #409)
5. Click on API Documentation tab
6. You are back on 1.5 API documentation overview
----
alpha and "ready to be released once few hurdles get cleared"??? Aren't there first going to be one or more betas?

Somebody jumped the gun on the documentation.

How many more years?

The documentation should reflect current reality. And, then, once 1.5 IS finally released people with old projects (or, hopefully, converting old projects to 1.5) will still need to reference the 1.4 documentation.

I'm going to stop responding to questions about JQM on the forum. "It's dead, Jim".

**Comment by jtara** [comment]
I guess the only real issue here is #409. The numbskull tabs are the numbskull tabs. I see it works the same idiotic way for every version.

One would think you go to documentation for a version, and then you can click tabs for demos, download, API documentation, Themes, etc.

But all the tabs take you to current version, no matter what you started with.

**Comment by apsdehal** [comment]
Let me work on fixing this. Would try to tackle this on weekend. And yes, there were some sync issues in release and there would be a beta.
